### ISSUE TITLE
Equation for Latitude/Longitude?

### ISSUE THREAD

**Issue by MatinF** [spot2000/Volkswagen-MEB-EV-CAN-parameters#3]
Hi - thanks for this great repo!

I wanted to check if anyone had success identifying the equation for Latitude/Longitude?

Below is an example of the multiframe response where the latitude should be around 47-48 and the longitude should be between 8-9.

![image](https://user-images.githubusercontent.com/26184427/188603230-4f193a41-9f80-4b38-8258-9b5c8909c422.png)

**Comment by spot2000** [comment]
﻿Hi. Yes we have decoded it. See source code for evDash.

It’s very easy. It’s encoded as ascii. ;)

Mvh
Conny Nikolaisen

Skickat från min iPhone 11 Pro Max

6 sep. 2022 kl. 11:47 skrev Martin Falch ***@***.***>:

﻿

Hi - thanks for this great repo!

I wanted to check if anyone had success identifying the equation for Latitude/Longitude?

Below is an example of the multiframe response where the latitude should be around 47-48 and the longitude should be between 8-9.

[image]<https://user-images.githubusercontent.com/26184427/188603230-4f193a41-9f80-4b38-8258-9b5c8909c422.png>

**Comment by MatinF** [comment]
Hi Conny, thanks for the quick response! 

I tried looking through the source code, but I was unable to specifically find the Skoda Enyaq Latitude/Longitude details. Are you able to specify where to look for it? Thanks a lot!

**Comment by MatinF** [comment]
I think I may have found it via below:

```
if (liveData->commandRequest.equals("222430")) // LAT/LON/ALT
      {
        // 6224303138B0333627362E3022450000003438B031322733342E33224E000002A1AA
        //       ^^^^

        // Parse latitude
        uint8_t b;
        float val;
        String tmp = "";
        for (uint16_t i = 0; i < 14; i++)
        {
          b = liveData->hexToDecFromResponse(6 + (i * 2), 6 + (i * 2) + 2, 1, false);
          if (b == 0)
            break;
          tmp += char((b > 100) ? 95 : b);
        }
        // 18_36'6.0"E
        val = convertLatLonToDecimal(tmp);
        if (val != 0)
          liveData->params.gpsLon = val;


        // Parse logitude
        tmp = "";
        for (uint16_t i = 0; i < 14; i++)
        {
          b = liveData->hexToDecFromResponse(34 + (i * 2), 34 + (i * 2) + 2, 1, false);
          if (b == 0)
            break;
          tmp += char((b > 100) ? 95 : b);
        }

        // 48_12'34.3"N
        val = convertLatLonToDecimal(tmp);

        
        if (val != 0)
          liveData->params.gpsLat = val;
        // altitude
        int16_t alt = liveData->hexToDecFromResponse(62, 66, 2, false) - 501;
        if (alt > -500)
          liveData->params.gpsAlt = alt;
      }
```
I'm a bit unfamiliar with the syntax, though. Can you clarify what the bit start and length is for the bits related to Latitude and Longitude? And what would be the scale/offset?

Thanks a ton again for all your work on this!

**Comment by spot2000** [comment]
Yes. That’s the correct code.

Mvh
Conny Nikolaisen

Skickat från min iPhone 11 Pro Max

6 sep. 2022 kl. 12:28 skrev Martin Falch ***@***.***>:

﻿

I think I may have found it via below:

if (liveData->commandRequest.equals("222430")) // LAT/LON/ALT
      {
        // 6224303138B0333627362E3022450000003438B031322733342E33224E000002A1AA
        //       ^^^^

        // Parse latitude
        uint8_t b;
        float val;
        String tmp = "";
        for (uint16_t i = 0; i < 14; i++)
        {
          b = liveData->hexToDecFromResponse(6 + (i * 2), 6 + (i * 2) + 2, 1, false);
          if (b == 0)
            break;
          tmp += char((b > 100) ? 95 : b);
        }
        // 18_36'6.0"E
        val = convertLatLonToDecimal(tmp);
        if (val != 0)
          liveData->params.gpsLon = val;


        // Parse logitude
        tmp = "";
        for (uint16_t i = 0; i < 14; i++)
        {
          b = liveData->hexToDecFromResponse(34 + (i * 2), 34 + (i * 2) + 2, 1, false);
          if (b == 0)
            break;
          tmp += char((b > 100) ? 95 : b);
        }

        // 48_12'34.3"N
        val = convertLatLonToDecimal(tmp);


        if (val != 0)
          liveData->params.gpsLat = val;
        // altitude
        int16_t alt = liveData->hexToDecFromResponse(62, 66, 2, false) - 501;
        if (alt > -500)
          liveData->params.gpsAlt = alt;
      }


I'm a bit unfamiliar with the syntax, though. Can you clarify what the bit start and length is for the bits related to Latitude and Longitude? And what would be the scale/offset?

Thanks a ton again for all your work on this!

**Comment by MatinF** [comment]
Thanks I think I see the logic now of converting the bytes to ASC, then back. That's unfortunately beyond the domain of simple DBC files it seems :-P Appreciate the fast support!
